name: Publish GitHub Action

on:
  push:
    branches: [ main ]

jobs:
  publish-github-action:
    runs-on: ubuntu-latest
    steps:
      - name: 'Project holobranch github-action to v1'
        uses: JarvusInnovations/hologit@actions/projector/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HAB_LICENSE: accept
        with:
          holobranch: github-action
          commit-to: v1
