name: "Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  # unit tests
  jest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm ci
    - run: npm test

  # test action works running from the graph
  success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - run: npm install
    - uses: ./
      with:
        run: |
          PORT=1212 node test/server.js &
          PORT=2121 node test/server.js &
          PORT=3232 node test/server.js &
        wait-on: |
          http://localhost:1212/bar
          tcp:localhost:1212
          http://localhost:2121/bar
          tcp:localhost:2121
          http://localhost:3232/bar
          tcp:localhost:3232
        log-output-resume: stderr
        tail: true
        wait-for: 5m
        log-output: stderr,stdout
    - run: sleep 30 # allow stderr to get output in the background
